spring:
  jpa:
    show-sql: false

server:
  ssl:
    enabled: false
  forward-headers-strategy: framework

logging:
  level:
    com.labo.anapath: INFO

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
